name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches: [ develop, main ]

jobs:
  build-apk:
    runs-on: ubuntu-latest
    container: kivy/buildozer:latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build Android APK with Buildozer
      run: |
        buildozer android debug

    - name: Upload Mobile APK
      uses: actions/upload-artifact@v4
      with:
        name: NilgiriDairyPro-Mobile-APK
        path: bin/*.apk
